name: CI

on:
  push:
    branches:
      - github-compile
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: compile
        uses: ./.github/actions/build-matrix
        with:
          platforms: "atari,apple2,adam,coco,c64,msdos"
          target: "disk"
