name: Compile (Reusable)

on:
  workflow_call:
    inputs:
      platform:
        description: "Optional single platform to build"
        required: false
        type: string

jobs:
  compile:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        # If 'platform' input is empty, build all of these
        platform: ${{ fromJSON(inputs.platform) || '["atari","apple2","adam","coco","c64","rs232"]' }}

    steps:
      - uses: actions/checkout@v4

      - name: Build inside Docker
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            fozztexx/defoogi:latest \
            make -f Makefile.${{ matrix.platform }
